<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_financial</name>
   <tag></tag>
   <elementGuidId>350a5d4d-da4d-4814-8491-31966fa76a11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fuse-layout']/div/div/div/div/div/div/ul/li/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.sc-kEYyzF.sc-eHgmQL.hyfYOc.MuiTypography-body1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root sc-kEYyzF sc-eHgmQL hyfYOc MuiTypography-body1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>financial</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fuse-layout&quot;)/div[@class=&quot;flex flex-1 flex-col overflow-hidden relative&quot;]/div[@class=&quot;jss1372&quot;]/div[@class=&quot;jss1373&quot;]/div[@class=&quot;jss1374&quot;]/div[@class=&quot;sc-dxgOiQ ewQdbp&quot;]/div[@class=&quot;sc-ckVGcZ dHFJcZ&quot;]/ul[@class=&quot;sc-kkGfuU VctWP&quot;]/li[@class=&quot;sc-iAyFgw rQmRk&quot;]/p[@class=&quot;MuiTypography-root sc-kEYyzF sc-eHgmQL hyfYOc MuiTypography-body1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fuse-layout']/div/div/div/div/div/div/ul/li/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maham Kheiriyeh'])[1]/following::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme Settings'])[1]/preceding::p[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Style'])[1]/preceding::p[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='financial']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/p</value>
   </webElementXpaths>
</WebElementEntity>
